#!/bin/bash

# Log to file
echo "Postinstall script for MorseCodeInputMethod started" >> /var/log/install.log

# Get the current logged-in user
USER=$(stat -f "%Su" /dev/console)
USER_HOME=$(dscl . -read /Users/$USER NFSHomeDirectory | awk '{print $2}')

# Define the paths
INPUT_METHODS_PATH="$USER_HOME/Library/Input Methods"
APP_PATH="$INPUT_METHODS_PATH/MorseCodeInputMethod.app"
error_occurred=false

# Check if .app exists and remove it
if [ -d "$APP_PATH" ]; then
    chown -R "$USER:staff" "$USER_HOME/Library/Input Methods/MorseCodeInputMethod.app"
    echo "Changed ownership for MorseCodeInputMethod.app" >> /var/log/install.log
else
    echo "MorseCodeInputMethod.app not found. Cannot change permissions." >> /var/log/install.log
    error_occurred=true
fi

if [ "$error_occurred" = true ]; then
    echo "Morse Code Input Method Postinstall script encountered errors." >> /var/log/install.log
    exit 1
fi

# Log success
echo "MorseCodeInputMethod files ownership change completed successfully" >> /var/log/install.log

exit 0
